OpenLiberty/guide-microprofile-metrics

README.adoc
Sorry--just saw a missing comma and missing articles ("the"). I will leave this alone now!
=> Last ID edits!

README.adoc, finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java, start/src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java
Is that maybe better for `absolute` field ?
=> Modified Adoc

README.adoc, finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java
=> Handle metrics feedback

finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java, start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java, start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
OpenLiberty/guides-common#95
OpenLiberty/guides-common#137
=> Refactor invetory

README.adoc, finish/pom.xml, finish/src/main/liberty/config/server.xml, start/pom.xml
* Updating feature versions
* Converting dependencies to new install feature
* Updating README
=> Updating feature versions and converting dependencies

finish/src/main/liberty/config/server.xml
- Fixed #69 due to default keystore type changes in recent OL builds
=> Fixed daily build failure

finish/pom.xml, finish/src/main/liberty/config/server.xml, start/pom.xml
=> Merge qa to master: update feature version

finish/pom.xml, start/pom.xml
Issue:
OpenLiberty/guides-common#268
=> Updating Dependencies 

finish/pom.xml, finish/src/main/liberty/config/server.xml, start/pom.xml
Reduce the SRVE9967W warnings from the messages.log
#75
=> Merge qa to master: Updating Dependencies

.travis.yml, README.adoc, finish/pom.xml, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java, scripts/travisTest.sh, start/pom.xml, start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
- use junit5 test execution order
- remove unused dependencies
- addressing https://github.com/OpenLiberty/guides-common/issues/217
- using travisTest.sh (with comments) from template
=> use junit5 test execution order

README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java, start/pom.xml, start/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, start/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java
- use space instead of `\\s+`
- update the plugins and dependencies version
=> fix the MetricsIT

.travis.yml, README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java, finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsTest.java, finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java, scripts/travisTest.sh, start/pom.xml, start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, start/src/main/java/io/openliberty/guides/inventory/InventoryUtils.java, start/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, start/src/main/liberty/config/server.xml, start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, start/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
* mpMetrics2.0 updates
* Added tags to metrics guide
* Fixed review feedback
* Reverted the description changes
* Minor update on the output
* Updated annotation more info link
* Addressed peer review feedback
* Fixed SME feedback
* Addressed text suggestions
* Addressed text suggestions
* Minor text edit
* Minor changes for YK's feedback
* Dev mode mpMetrics2x (#88)
* simplified pom and tests
* Update MetricsIT with proper metric names and devmode test cases
* fix gauge metric spelling
* fix license years
* add predefined server.xml
* fix hotspots for MetricsIT
* use JUnit5
* Modified description of MetricsIT test cases in README
=> Mp metrics2x (#84)

finish/pom.xml, finish/src/main/webapp/index.html, start/pom.xml, start/src/main/webapp/index.html
- Versions specified at plugin
- Changed Jupiter dependancy
- Removed \<failOnMissingWebXml\> tag
- Removed extra div tag
=> pom.xml updates

.travis.yml, README.adoc, finish/pom.xml, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java, scripts/travisTest.sh, start/pom.xml, start/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
=> Merge qa to master: fix travis automation

start/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, start/src/main/liberty/config/server.xml
https://github.com/OpenLiberty/guide-microprofile-metrics/issues/103
=> Update inventory manager.

README.adoc
=> Merge qa to master: typo micorservices

README.adoc
PR: #126 
Issue: OpenLiberty/guides-common#514
=> Merge qa to master: add cd command

.github/workflows/maven.yml, .travis.yml
Issue: https://github.com/OpenLiberty/guides-common/issues/531
=> Migrating to GH actions

.github/workflows/maven.yml, .travis.yml, README.adoc
PR: #128 
Issue: https://github.com/OpenLiberty/guides-common/issues/531
=> Merge qa to master: use github action to test qa branch

finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java
=> Merge qa to master: revert to use \\s+

.github/workflows/test.yml, finish/src/test/java/it/io/openliberty/guides/metrics/MetricsIT.java
- PR: #139 
- Issue: https://github.com/OpenLiberty/guides-common/issues/532
=> Merge qa to master: Enable PR checker

.github/workflows/triggerConversion.yml
Co-authored-by: Jakub F Pomykala <Jakub.Pomykala@ibm.com>
=> Merge qa to master: Adding action for cloud-hosted-guides (#141)

README.adoc
add cloud-hosted guide instructions
=> Merge qa to master: Update README.adoc (#144)

README.adoc
bold an url in the cloud-hosted instrunction
=> Merge qa to master: Update README.adoc (#146)
